{% set build = 0 %}
{% set strbuild = "build_" + build|string %}
{% set version = "2020.04.08" %}

{% set sha256 = "1f9e83570f0670511998f609a2b4b3ddd5dc02563b052b6cd3af24a59452cece" %}

package:
  name: moose
  version: {{ version }}

source:
  url: https://mooseframework.org/source_packages/moose-env.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}  # [linux,osx]
  string: {{ strbuild }}
  skip: true # [win]

requirements:
  build:
    - moose-libmesh {{ moose_libmesh }}

  run:
    - moose-libmesh {{ moose_libmesh }}

test:
  commands:
    - test -f $PREFIX/share/moose

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'The Multiphysics Object-Oriented Simulation Environment (MOOSE) is a finite-element, multiphysics framework primarily developed by Idaho National Laboratory. This superficial module (moose) if a future placeholder for binary releases of MOOSE.'

extra:
  recipe-maintainers:
    - milljm
