{% set name = "moose-compilers" %}
{% set version = "2020.01.28" %}
{% set sha256 = "f8236c163aebbf8894381b7f71c42f3f3beeff6d8aee69b8a829cd76f7d5bd7a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://mooseframework.org/source_packages/moose-compilers.tar.gz
  sha256: {{ sha256 }}

build:
  number: 7  # [linux,osx]
  skip: true # [win]

requirements:
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - libpng
    - clang-tools  # [osx]

test:
  commands:
    - test -f $PREFIX/share/moose-compilers

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'This superficial module (moose-compilers) acts as a top-level module designed to provide all dependencies required in order to build and support MOOSE based developement.'

extra:
  recipe-maintainers:
    - milljm
