CONDA_BUILD_SYSROOT:           # [osx]
  - /opt/MacOSX10.9.sdk        # [osx]

macos_min_version:             # [osx]
  - 10.9                       # [osx]

macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]

MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.9                       # [osx]

mpi:
  - moose-mpich

SHORT_VTK_NAME:
  - 6.3

netcdf:
 - 4.6.2

moose_petsc:
 - 3.11.4 build_1

moose_libmesh_vtk:
 - 6.3.0 build_1

pin_run_as_build:
  moose_petsc: x.x.x
  moose_libmesh_vtk: x.x.x
