CONDA_BUILD_SYSROOT:           # [osx]
  - /opt/MacOSX10.9.sdk        # [osx]

macos_min_version:             # [osx]
  - 10.9                       # [osx]

macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]

MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.9                       # [osx]

mpi:
  - moose-mpich

SHORT_VTK_NAME:
  - 8.2 # [osx]
  - 6.3 # [linux]

moose_dev:
 - 2020.01.27

moose_libmesh_vtk:
  - 8.2.0 # [osx]
  - 6.3.0 # [linux]

pin_run_as_build:
  moose_dev: x.x.x
  moose_libmesh_vtk: x.x.x
