{% set name = "moose-libmesh" %}
{% set version = "81589c1acb86765a0a1981b7fef5328e91fb92ab" %}
{% set friendly_version = "2020.01.27" %}
{% set sha256 = "8f37b5d52ad764f8da5594a7b608fd8df6836038c0c187046861307cca0345bf" %}
{% set metaphysicl_version = "78f338a1508b4010a39a34d9fec9ee6247afaecf" %}
{% set metaphysicl_sha256 = "30ead616f1aad634ce270db2688f8c2b799a1f3b6a2f726a3bbf5abe1f923ac7" %}

package:
  name: {{ name }}
  version: {{ friendly_version }}

source:
  - url: https://github.com/libMesh/libmesh/archive/{{ version }}.tar.gz
    fn: libmesh-{{ version }}.tar.gz
    folder: src/github.com/libMesh/libmesh
    sha256: {{ sha256 }}
  - url: https://github.com/roystgnr/MetaPhysicL/archive/{{ metaphysicl_version }}.tar.gz
    fn: metaphysicl-{{ metaphysicl_version }}.tar.gz
    folder: metaphysicl
    sha256: {{ metaphysicl_sha256 }}

build:
  number: 0                                             # [linux,osx]
  skip: true                                            # [win]

requirements:
  build:
    - pkg-config
    - cctools                                           # [osx]
    - ld64                                              # [osx]
    - moose-dev {{ moose_dev }}
    - moose-libmesh-vtk {{ moose_libmesh_vtk }}

  run:
    - moose-dev
    - moose-libmesh-vtk

test:
  commands:
    - test -f $PREFIX/libmesh/lib/libmesh_opt.dylib     # [osx]
    - test -f $PREFIX/libmesh/lib/libmesh_opt.so        # [linux]
    - test -f $PREFIX/libmesh/lib/libmetaphysicl.dylib  # [osx]
    - test -f $PREFIX/libmesh/lib/libmetaphysicl.so     # [linux]

about:
  home: http://libmesh.github.io/
  license: LGPL
  summary: 'The libMesh library provides a framework for the numerical simulation of partial differential equations using arbitrary unstructured discretizations on serial and parallel platforms'

extra:
  recipe-maintainers:
    - milljm
