{% set build = 0 %}
{% set strbuild = "build_" + build|string %}
{% set version = "2020.04.08" %}

{% set libmesh_version = "179e8c8c2dcbfcc01311bd6f5044a9534aa21584" %}
{% set libmesh_sha256 = "87eb978d81256536ba6b23f40a5373b7338ce9af6f65da06045b393d0384c327" %}

{% set timpi_version = "e0850710c516f8ee6cfb878d132a149f89dbf9dd" %}
{% set timpi_sha256 = "eb0d80da298cfcdd28b17c49e0f8e03c0407b6d4e4929ee1a42b3b1d144b461d" %}

{% set metaphysicl_version = "736b63c98747b89209e09ff83b56ee07f9f9abad" %}
{% set metaphysicl_sha256 = "d40a3c9780d1d5ec16f83c213a0bed7965325877dd729e4c3d59bde7424fbe41" %}

package:
  name: moose-libmesh
  version: {{ version }}

source:
  - url: https://github.com/libMesh/libmesh/archive/{{ libmesh_version }}.tar.gz
    fn: libmesh-{{ libmesh_version }}.tar.gz
    folder: src/github.com/libMesh/libmesh
    sha256: {{ libmesh_sha256 }}

  - url: https://github.com/libMesh/TIMPI/archive/{{ timpi_version }}.tar.gz
    fn: timp-{{ timpi_version }}.tar.gz
    folder: timpi
    sha256: {{ timpi_sha256 }}

  - url: https://github.com/roystgnr/MetaPhysicL/archive/{{ metaphysicl_version }}.tar.gz
    fn: metaphysicl-{{ metaphysicl_version }}.tar.gz
    folder: metaphysicl
    sha256: {{ metaphysicl_sha256 }}

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: true                                            # [win]

requirements:
  build:
    - pkg-config
    - cctools                                           # [osx]
    - ld64                                              # [osx]
    - moose-libmesh-vtk {{ moose_libmesh_vtk }}
    - moose-petsc {{ moose_petsc }}

  run:
    - pkg-config
    - libnetcdf {{ netcdf }}                            # [linux]
    - moose-libmesh-vtk {{ moose_libmesh_vtk }}
    - moose-petsc {{ moose_petsc }}

test:
  commands:
    - test -f $PREFIX/libmesh/lib/libmesh_opt.dylib     # [osx]
    - test -f $PREFIX/libmesh/lib/libmesh_opt.so        # [linux]
    - test -f $PREFIX/libmesh/lib/libtimpi_opt.dylib    # [osx]
    - test -f $PREFIX/libmesh/lib/libtimpi_opt.so       # [linux]
    - test -f $PREFIX/libmesh/lib/libmetaphysicl.dylib  # [osx]
    - test -f $PREFIX/libmesh/lib/libmetaphysicl.so     # [linux]

about:
  home: http://libmesh.github.io/
  license: LGPL
  summary: 'The libMesh library provides a framework for the numerical simulation of partial differential equations using arbitrary unstructured discretizations on serial and parallel platforms'

extra:
  recipe-maintainers:
    - milljm
