vtk_version:
  - 8.2.0 # [osx]
  - 6.3.0 # [linux]

friendly_version:
  - 8.2 # [osx]
  - 6.3 # [linux]

sha256:
  - 34c3dc775261be5e45a8049155f7228b6bd668106c72a3c435d95730d17d57bb # [osx]
  - 92a493354c5fa66bea73b5fc014154af5d9f3f6cee8d20a826f4cd5d4b0e8a5e # [linux]

CONDA_BUILD_SYSROOT:           # [osx]
  - /opt/MacOSX10.9.sdk        # [osx]

macos_min_version:             # [osx]
  - 10.9                       # [osx]

macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]

MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.9                       # [osx]

mpi:
  - moose-mpich

moose_mpich:
  - 3.3.2

pin_run_as_build:
  moose_mpich: x.x.x
