python:
 - 3.7
 - 3.6

vtk:
 - 8.2.0 py37hcba847f_203 # [osx]
 - 8.2.0 py36hcba847f_203 # [osx]
 - 8.2.0 py37hfdee58b_203 # [linux]
 - 8.2.0 py36hfdee58b_203 # [linux]

zip_keys:
 - python
 - vtk

pin_run_as_build:
 python: x.x
