{% set name = "autojump" %}
{% set version = "22.5.3" %}
{% set sha256 = "00daf3698e17ac3ac788d529877c03ee80c3790472a85d0ed063ac3a354c37b1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/wting/{{ name }}/archive/release-v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 1  # [osx]
  skip: true # [win,linux]

requirements:
  build:
    - python

test:
  commands:
    - test -f $PREFIX/bin/autojump

about:
  home: https://github.com/wting/autojump
  license: GNU
  summary: 'autojump is a faster way to navigate your filesystem. It works by maintaining a database of the directories you use the most from the command line.'

extra:
  recipe-maintainers:
    - milljm
